"""empty message

Revision ID: 99dbc74ec54f
Revises: 44aa712742ae
Create Date: 2025-05-29 12:01:35.023221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dbc74ec54f'
down_revision = '44aa712742ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('expected_delivery', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('expected_delivery')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
